name: 'Run-in-reMarkable-Action'
description: Run a script in a reMarkable tablet QEMU instance
author: Eeems
branding:
  icon: tablet
  color: white
inputs:
  run:
    description: Script to execute in the QEMU instance
    required: true
  setup:
    description: Script to execute during docker image build so that it can be cached between runs
    required: false
    default: ''
  path:
    description: Folder to sync with the device. This will be available at /src
    required: false
    default: ${{ github.workspace }}
  fw_version:
    description: reMarkable OS version to run in
    required: false
    default: 2.15.1
  clean_cache:
    description: Clean the local docker cache before running
    required: false
    type: boolean
    default: false
runs:
  using: composite
  steps:
    - name: Checkout rm-docker repository
      uses: actions/checkout@v4
      with:
        repository: timower/rM-docker
        ref: 2593f981f0264d0b6dba49192044ce9cd312bfce
        fetch-depth: 1
        path: .rm-docker-repo
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Prep build
      shell: bash
      run: |
        mkdir -p "$temp_dir/rira"
        cp -al "$action/entrypoint.sh" "$tmp/rira/entrypoint.sh"
        sed "
          /#insert=rm-docker\/Dockerfile/r $workspace/.rm-docker-repo/Dockerfile
          /#insert=rm-docker\/Dockerfile/d
        " "$action/Dockerfile.in" > "$temp_dir/rira/build.Dockerfile"
        echo "#!/bin/sh" > "$temp_dir/rira/run.sh"
        echo "cd /opt/tmp/src" >> "$temp_dir/rira/run.sh"
        echo "$script" >> "$temp_dir/rira/run.sh"
        chmod +x "$temp_dir/rira/run.sh"
        echo "#!/bin/sh" > "$temp_dir/rira/setup.sh"
        echo "$setup" >> "$temp_dir/rira/setup.sh"
        chmod +x "$temp_dir/rira/setup.sh"
      env:
        script: ${{ inputs.run }}
        setup: ${{ inputs.setup }}
        workspace: ${{ github.workspace }}
        temp_dir: ${{ runner.temp }}
        action: ${{ github.action_path }}
    - name: Clean old buildx cache
      if: ${{ inputs.clean_cache }}
      shell: bash
      run: |
        docker buildx prune -f
        docker image prune -f
    - name: Build image
      uses: docker/build-push-action@v5
      with:
        tags: rm-docker:run-in-remarkable-action
        target: run-in-remarkable-action
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          fw_version=${{ inputs.fw_version }}
        build-contexts: |
          gha=${{ runner.temp }}/rira
        context: ${{ github.workspace }}/.rm-docker-repo
        file: ${{ runner.temp }}/rira/build.Dockerfile
    - name: Build codexctl
      shell: bash
      run: |
        cd "$workspace"
        docker run \
          --rm \
          -v "$src_path":/src \
          rm-docker:run-in-remarkable-action
      env:
        src_path: ${{ inputs.path }}
        workspace: ${{ github.workspace }}
