name: 'Run-in-reMarkable-Action'
description: Run a script in a reMarkable tablet QEMU instance
author: Eeems
branding:
  icon: tablet
  color: white
inputs:
  run:
    description: Script to execute in the QEMU instance
    required: true
  setup:
    description: Script to execute during docker image build so that it can be cached between runs
    required: false
    default: ''
  path:
    description: Folder to sync with the device. This will be available at /src
    required: false
    default: ${{ github.workspace }}
  fw_version:
    description: reMarkable OS version to run in
    required: false
    default: 2.15.1
runs:
  using: composite
  steps:
    - name: Checkout rm-docker repository
      uses: actions/checkout@v4
      with:
        repository: timower/rM-docker
        ref: 2593f981f0264d0b6dba49192044ce9cd312bfce
        fetch-depth: 1
        path: .rm-docker-repo
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Prep build
      shell: bash
      run: |
        cd "${{ github.action_path }}"
        mkdir -p "${{ runner.temp }}/rira"
        cp -l "${{ github.action_path }}/entrypoint.sh" "${{ runner.temp }}/rira/"
        sed '
          /#insert=rm-docker\/Dockerfile/r ${{ github.workspace }}/.rm-docker-repo/Dockerfile
          /#insert=rm-docker\/Dockerfile/d
        ' Dockerfile.in > "${{ runner.temp }}/rira/build.Dockerfile"
        echo "#!/bin/sh" > "${{ runner.temp }}/rira/build.sh"
        echo "$script" >> "${{ runner.temp }}/rira/build.sh"
        chmod +x "${{ runner.temp }}/rira/build.sh"
        echo "#!/bin/sh" > "${{ runner.temp }}/rira/setup.sh"
        echo "$setup" >> "${{ runner.temp }}/rira/setup.sh"
        chmod +x "${{ runner.temp }}/rira/setup.sh"
      env:
        script: ${{ inputs.run }}
        setup: ${{ inputs.setup }}
    - name: Build image
      uses: docker/build-push-action@v5
      with:
        tags: rm-docker:run-in-remarkable-action
        target: run-in-remarkable-action
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          fw_version=${{ inputs.fw_version }}
        build-contexts: |
          gha=${{ runner.temp }}/rira
        context: ${{ github.workspace }}/.rm-docker-repo
        file: ${{ runner.temp }}/rira/build.Dockerfile
    - name: Build codexctl
      shell: bash
      run: |
        docker run \
          --rm \
          -v ${{ inputs.path }}:/src \
          rm-docker:run-in-remarkable-action
