#syntax=docker/dockerfile:1.4
#insert=rm-docker/Dockerfile

FROM qemu-toltec as run-in-remarkable-action

RUN <<EOT
    set -ex
    export DEBIAN_FRONTEND="noninteractive"
    apt-get update
    apt-get install -y rsync
    rm -rf /var/lib/apt/lists/*
EOT

COPY --from=gha setup.sh /opt/setup.sh

RUN <<EOT
    set -ex
    run_vm.sh -serial null -daemonize
    wait_ssh.sh
    scp /opt/setup.sh root@localhost:/opt/bin
    ssh root@localhost 'bash -l -c setup.sh'
    save_vm.sh
EOT

COPY --from=gha build.sh /opt/build.sh

RUN <<EOT
    set -ex
    run_vm.sh -serial null -daemonize
    wait_ssh.sh
    scp /opt/build.sh root@localhost:/opt/bin
    rm /opt/build.sh
    save_vm.sh
EOT

ADD entrypoint.sh /opt/bin/entrypoint.sh
CMD entrypoint.sh
