#syntax=docker/dockerfile:1.4
#insert=rm-docker/Dockerfile

FROM qemu-toltec as run-in-remarkable-action

RUN <<EOT
    set -ex
    export DEBIAN_FRONTEND="noninteractive"
    apt-get update
    apt-get install -y rsync
    rm -rf /var/lib/apt/lists/*
EOT

COPY --from=gha wait_for_timesync.sh /opt/wait_for_timesync.sh
COPY --from=gha setup.sh /opt/setup.sh

RUN <<EOT
    set -ex
    run_vm.sh -serial null -daemonize
    wait_ssh.sh
    scp /opt/wait_for_timesync.sh root@localhost:/opt/bin
    scp /opt/setup.sh root@localhost:/opt/bin
    ssh root@localhost 'bash -l -c wait_for_timesync.sh'
    ssh root@localhost 'bash -l -c setup.sh'
    save_vm.sh
EOT

COPY --from=gha run.sh /opt/run.sh

RUN <<EOT
    set -ex
    run_vm.sh -serial null -daemonize
    wait_ssh.sh
    ssh root@localhost 'bash -l -c wait_for_timesync.sh'
    scp /opt/run.sh root@localhost:/opt/bin
    rm /opt/run.sh
    save_vm.sh
EOT

COPY --from=gha entrypoint.sh /opt/bin/entrypoint.sh
CMD entrypoint.sh
