name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'
jobs:
  test-basic:
    name: Test basic
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fw_version:
          - 2.15.1
          - 3.3.2
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - uses: ./
        with:
          setup: |
            touch /foo
          run: |
            if ! [ -f /foo ]; then
              echo "::error::/foo missing, did setup not run?"
              exit 1
            fi
            if ! opkg update; then
              echo "::error::Failed to synch toltec and entware repositories"
              exit 1
            fi
